# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b449cfddf4eb7e2a9af6dd79f24f82e0114011cd87f84e01d262a3ccdfa5ec29a37182bb1a3a60afaeba0ef5ec87f2501e91bd0ab6363efb1552d13eeedd163e

test:
  secret_key_base: f8b077d470792dc3ef8ef9ee189b2e72bba3baeb108fec1b4279c579488d8423ca38927dcc979e1f8d6e5cb3e312c357cfd015918fbdab5d9ead62373cd09937

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
